[package]
name = "tomb_of_the_moon"
version = "0.1.0"
edition = "2021"


[dependencies]
bracket-lib = { version = "~0.8", features = ["serde"] }
specs = { version = "0.20.0", features = ["serde"] }
specs-derive = "0.4.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.39"